### ISSUE TITLE
Github plugin

### ISSUE THREAD

**Issue by aslakhellesoy** [cucumber-attic/gherkin-editor#7]
Now that Github allows files to be edited with [Ace](https://github.com/blog/905-edit-like-an-ace) we can piggy-back on that.

We'd have to implement a userscript (see [codeshelver](https://www.codeshelver.com/) for an example) that adds code completion etc. on top of the github-supplied editor.

Code completion data can be taken from a well-known location in git. An example is [here](https://github.com/cucumber/cucumber-jvm/blob/master/picocontainer/.cucumber/meta.json). This file will be generated when Cucumber runs, and developers will check it into git.

**Comment by jbpros** [comment]
I love the idea. Are you already on it? Do you want some help?

**Comment by aslakhellesoy** [comment]
I haven't started on it - no. I guess step one would be to update gherkin-editor to use whatever version github is using. Feel free to start this on a `github` branch!

**Comment by jbpros** [comment]
Ok cool, I'm on it. I've been hacking a bit on gherkin-editor lately; I'm getting impatient to plug -js into it ;)

**Comment by aslakhellesoy** [comment]
C9 now has a code completion widget: http://cloud9ide.posterous.com/complete-your-code

Unfortunately this is not in Ace - it was added to C9 (which is built on top of ace):
https://github.com/ajaxorg/cloud9/commit/09f2ada631c07e1ed1925916c959f6903215f93d

I am trying to get them to move it to Ace: https://github.com/ajaxorg/ace/issues/110 (see my last comment)

**Comment by jbpros** [comment]
It looks like the plugin won't make it into Ace with ease, unfortunately.

**Comment by aslakhellesoy** [comment]
Poked a little around in the console:

``` javascript
// get a ref to the editor
var editor = window.editor.ace;

editor.getSession().on('change', function(e) {
  console.log('hijacked!');
});

```

:-P

**Comment by aslakhellesoy** [comment]
A good first step would be to write a userscript that looks at the extension of the URL, and if it ends with `.feature`, sets the gherkin mode. It's currently here:

https://github.com/cucumber/ace/blob/gherkin-mode/lib/ace/mode/gherkin.js
https://github.com/cucumber/ace/blob/gherkin-mode/lib/ace/mode/gherkin_highlight_rules.js

(We should add this to the userscript)

**Comment by aslakhellesoy** [comment]
W00t - with a little copy and paste into the console of the code above I managed to get syntax highlighting in an editor running on github!

While I remember it - we should add https://github.com/josephg/ShareJS at one point for collaborative editing. Not sure how well that will work with code completion though...

**Comment by jbpros** [comment]
![Gherkin highlighting on Github editor](http://f.cl.ly/items/2F1v350n0r2M2P3D242k/Screen%20Shot%202011-11-04%20at%2021.11.51.png)

Thanks @aslakhellesoy, that was easy! Really cool stuff.

Here is [what I pasted](https://gist.github.com/1340378) into Chrome's console. I'm finishing the stepdef snippet stuff on cucumber.js and then I'll get back to this.

I didn't know about ShareJS, I tried some demo and it looks great too.

**Comment by aslakhellesoy** [comment]
Sweet! I read up on chrome extensions, and it looks like we can't use that - they have access to the same DOM but not js from the page (so no window.editor).

So I guess it's userscript, unless you have another suggestion?

**Comment by jbpros** [comment]
I can't think of any other alternative. A userscript should be fine :)

I was wondering... did you consider sending a pull request to ajaxorg/ace for Gherkin highlighting?

**Comment by aslakhellesoy** [comment]
I have considered it, but only after we support all i18n languages and the highlighting is well tested. We need to generate a highlighter per language. I think maybe the ace highlighter(s) should move to the https://github.com/cucumber/gherkin-syntax-highlighters project.

**Comment by aslakhellesoy** [comment]
Done!
- Check out https://github.com/cucumber/gherkin-github for a Github userscript (sorry - only visible to cucumber admins for now)
- Moved the syntax highlighting code to https://github.com/cucumber/gherkin-syntax-highlighters
